{{- if .Values.rhtpa.database.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '5'
  name: rhtpa-db
  namespace: {{ .Values.rhtpa.namespace }}
{{- end }}

