{{- if .Values.rhtpa.database.create }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: rhtpa-db-secret
  namespace: {{ .Values.rhtpa.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: '5'
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: {{ .Values.global.secretStore.kind }}
  target:
    name: {{ .Values.rhtpa.database.secretName }}
    template:
      type: Opaque
      data:
        username: {{ .Values.rhtpa.database.username }}
        database: {{ .Values.rhtpa.database.name }}
        password: "{{ `{{ .password }}` }}"
  data:
  - secretKey: password
    remoteRef:
      key: {{ .Values.rhtpa.database.passwordVaultKey }}
      property: db-password
{{- end }}

