apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: aws-credentials
  namespace: cert-manager
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: {{ .Values.global.secretStore.kind }}
  target:
    name: aws-credentials
    template:
      type: Opaque
      data:
        aws_access_key_id: "{{ `{{ .id }}` }}"
        aws_secret_access_key: "{{ `{{ .key }}` }}"
  data:
  - secretKey: id
    remoteRef:
      key: secret/hub/aws
      property: aws_access_key_id
  - secretKey: key
    remoteRef:
      key: secret/hub/aws
      property: aws_secret_access_key