{{- if .Values.certmgrOperator.credentialsRequests }}
{{- range .Values.certmgrOperator.credentialsRequests }}
{{- include "credential-request.validations" . }}
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: {{ .name | default (printf "cert-manager-%s" (randAlpha 5 | lower)) }}
  namespace: {{ .namespace | default $.Release.Namespace }}
spec:
{{- tpl (omit . "name" "namespace" | toYaml) $ | nindent 2 }}
{{- end }}
{{- end }}