global:
  localClusterDomain: local.example.com
  hubClusterDomain: hub.example.com

spiffe:
  csi:
    agentSocketPath: "/run/spire/agent-sockets"

spire:
  trustDomain: "{{ .Values.global.localClusterDomain }}"
  clusterName: "cluster"
  bundleConfigMap: "spire-bundle"

  agent:
    nodeAttestor:
      k8sPSATEnabled: "true"
    workloadAttestors:
      k8sEnabled: "true"
      workloadAttestorsVerification:
        type: "auto"
        hostCertBasePath: /var/lib/kubelet/pki
        hostCertFileName: ""

  oidcDiscoveryProvider:
    ingress:
      operatorManaged: "true"
      annotations:
        route.openshift.io/termination: reencrypt
      host: "spire-spiffe-oidc-discovery-provider.{{ .Values.global.localClusterDomain }}"
    service:
      name: spire-spiffe-oidc-discovery-provider
      port: 443

  server:
    ca:
      commonName: redhat.com
      country: US
      organization: Red Hat
    service:
      name: spire-server
      port: 443
    persistence:
      size: 5Gi
      accessMode: ReadWriteOnce
      storageClass: ""
    datastore:
      databaseType: sqlite3
      connectionString: /run/spire/data/datastore.sqlite3
      maxOpenConns: 100
      maxIdleConns: 10
      connMaxLifetime: 0
    federation:
      enabled: "false"
      federatesWith: []
      bundleEndpoint:
        profile: "https_spiffe"
      ingress:
        operatorManaged: "true"
        annotations:
          route.openshift.io/termination: passthrough
        host: "spire-server.{{ .Values.global.localClusterDomain }}"
