{{- if or .Values.keycloak.defaultConfig .Values.keycloak.realms }}
{{/*
Merge realms
*/}}
{{- $realms := .Values.keycloak.realms | default list }}
{{- if .Values.keycloak.defaultConfig }}
{{- $realms = append $realms .Values.keycloak.defaultRealm }}
{{- end }}
{{- range $realms }}
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: "{{ .realm }}-realm-import"
  namespace: "{{ $.Release.Namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  keycloakCRName: keycloak
  realm:
{{- toYaml . | nindent 4 }}
  placeholders:
    QTODO_ADMIN_PASSWORD:
      secret:
        name: {{ $.Values.keycloak.users.secretName }}
        key: qtodo-admin-password
    QTODO_USER1_PASSWORD:
      secret:
        name: {{ $.Values.keycloak.users.secretName }}
        key: qtodo-user1-password
    RHTAS_USER_PASSWORD:
      secret:
        name: {{ $.Values.keycloak.users.secretName }}
        key: rhtas-user-password
    RHTPA_USER_PASSWORD:
      secret:
        name: {{ $.Values.keycloak.users.secretName }}
        key: rhtpa-user-password
    QTODO_CLIENT_SECRET:
      secret:
        name: oidc-client-secret
        key: client-secret
    RHTPA_CLI_SECRET:
      secret:
        name: rhtpa-oidc-cli-secret
        key: client-secret
{{- end }}
{{- end }}