{{- if or .Values.keycloak.defaultConfig .Values.keycloak.realms }}
{{/*
Merge realms
*/}}
{{- $realms := .Values.keycloak.realms | default list }}
{{- if .Values.keycloak.defaultConfig }}
{{- $realms = append $realms .Values.keycloak.defaultRealm }}
{{- end }}
{{- range $realms }}
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: "{{ .realm }}-realm-import"
  namespace: "{{ $.Release.Namespace }}"
spec:
  keycloakCRName: keycloak
  realm:
{{- toYaml . | nindent 4 }}
  placeholders:
    QTODO_ADMIN_PASSWORD:
      secret:
        name: {{ $.Values.keycloak.users.secretName }}
        key: qtodo-admin-password
    QTODO_USER1_PASSWORD:
      secret:
        name: {{ $.Values.keycloak.users.secretName }}
        key: qtodo-user1-password
{{- end }}
{{- end }}