{{- if eq .Values.keycloak.adminUser.enabled true }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: keycloak-admin-user
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: {{ .Values.global.secretStore.kind }}
  target:
    name: {{ .Values.keycloak.adminUser.secretName }}
    template:
      type: Opaque
      data:
        username: "{{ .Values.keycloak.adminUser.username }}"
        password: "{{ `{{ .admin_password }}` }}"
  data:
  - secretKey: admin_password
    remoteRef:
      key: {{ .Values.keycloak.adminUser.passwordVaultKey }}
      property: admin-password
{{- end }}
