{{- if eq .Values.quay.enabled true }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: qtodo-quay-password
  namespace: {{ .Release.Namespace | default .Values.global.namespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: {{ .Values.global.secretStore.kind }}
  target:
    name: qtodo-quay-password
    template:
      type: Opaque
      data:
        password: "{{ `{{ .password }}` }}"
  data:
  - secretKey: password
    remoteRef:
      key: {{ .Values.registry.vaultPath }}
      property: {{ .Values.registry.passwordVaultKey }}
{{- end }}