---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: qtodo-registry-auth
  namespace: {{ .Release.Namespace | default .Values.global.namespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: {{ .Values.global.secretStore.kind }}
  target:
    name: qtodo-registry-auth
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .Values.registry.domain | default (printf "quay-registry-quay-quay-enterprise.%s" .Values.global.hubClusterDomain) }}": {
                "auth": "{{ `{{ printf "%s:%s" "` }}{{ .Values.registry.user }}{{ `" .password | b64enc }}` }}"
              }
            }
          }
  data:
  - secretKey: password
    remoteRef:
      key: {{ .Values.registry.vaultPath }}
      property: {{ .Values.registry.passwordVaultKey }}