apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  name: noobaa-default-backing-store
  namespace: {{ .Values.noobaa.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: pv-pool
  pvPool:
    numVolumes: {{ .Values.noobaa.pvPool.numVolumes | default 1 }}
    resources:
      requests:
        cpu: {{ .Values.noobaa.pvPool.resources.requests.cpu | quote }}
        memory: {{ .Values.noobaa.pvPool.resources.requests.memory | quote }}
        storage: {{ .Values.noobaa.pvPool.resources.requests.storage }}
      limits:
        cpu: {{ .Values.noobaa.pvPool.resources.limits.cpu | quote }}
        memory: {{ .Values.noobaa.pvPool.resources.limits.memory | quote }}