---
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
- name: image-registry-credentials
metadata:
  name: pipeline
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/syncOptions: ServerSideApply=true
secrets:
  - name: qtodo-registry-auth