# -- Dictionary of the global settings to configure this chart
# @default -- depends on the individual settings
global:
  secretStore:
    name: "vault-backend"
    kind: "ClusterSecretStore"

installerType: "argocd"

# -- String the channel to install cert-manager from (Defaults to "stable-v1")
operatorChannel: "stable-v1"

certmgrOperator:

  # -- List of DNS server (ip:port strings) to be used when doing DNS01 challenges (Defaults to [8.8.8.8:53, 1.1.1.1:53])
  # These are necessary for DNS01 ACME solver which needs outside DNS
  # servers and won't really work with openshift's internal split-view DNS servers
  # [https://cert-manager.io/docs/configuration/acme/dns01/#setting-nameservers-for-dns01-self-check](https://cert-manager.io/docs/configuration/acme/dns01/#setting-nameservers-for-dns01-self-check)
  nameservers:
    - 8.8.8.8:53
    - 1.1.1.1:53

  # -- Arguments to pass to the cert-manager controller (optional)
  # Example:
  # additionalArgs:
  #   - "--acme-http01-solver-nameservers=8.8.8.8:53,1.1.1.1:53"
  #   - "--v=2"
  additionalArgs: []

  # -- Issuers to use for the cert-manager (optional)
  # You can specify multiple issuers for different challenges.
  issuers:
    - acme:
        email: "validated-patterns-qe@redhat.com"
        server: "https://acme-staging-v02.api.letsencrypt.org/directory"
        privateKeySecretRef:
          name: "acme-account-key"
        solvers:
          - dns01:
              route53:
                region: "ap-southeast-1"
                accessKeyIDSecretRef:
                  name: "aws-credentials"
                  key: "aws_access_key_id"
                secretAccessKeySecretRef:
                  name: "aws-credentials"
                  key: "aws_secret_access_key"
                hostedZoneID: "Z001281810MV5UN93UQKQ"

  credentialsRequests:
    - name: aws
      secretRef:
        name: "aws-credentials"
        namespace: "cert-manager"
      providerSpec:
        apiVersion: cloudcredential.openshift.io/v1
        kind: "AWSProviderSpec"
        statementEntries:
        - effect: Allow
          action:
            - route53:GetChange
          resource: "arn:aws:route53:::change/*"
        - effect: Allow
          action:
            - route53:ChangeResourceRecordSets
            - route53:ListResourceRecordSets
          resource: "arn:aws:route53:::hostedzone/*"
#       -- can be removed if you specify the (optional) hostedZoneID.
        - effect: Allow
          action:
            - route53:ListHostedZones
          resource: "*"
