quay:
  namespace: quay-enterprise
  configBundleSecret:
    deploy: true
    name: quay-init-config-bundle-secret
  setup:
    admin:
      name: quayadmin
      email: quayadmin@example.com
    user:
      name: developer1
      email: developer1@myorg.com
  storage:
    postgres:
      size: 50Gi  # Default and minimum size is 50 Gi
    clairpostgres:
      size: 50Gi  # Default and minimum size is 50 Gi

job:
  image: registry.redhat.io/openshift4/ose-cli:latest

quay_config:
  org:
    name: devel
    email: devel@myorg.com
  repo: example

# Object Storage configuration - using NooBaa MCG
objectStorage:
  objectBucketClaim:
    name: quay-bucket
    bucketName: quay-datastore
    storageClass: openshift-storage.noobaa.io
