global:
  localClusterDomain: local.example.com

compliance:
  # ScanSetting configuration
  scanSetting:
    name: compliance-scan-setting
    # Enable automatic remediation
    autoApplyRemediations: true
    # Schedule scan 
    schedule: ""
    # Set scanning tolerations
    scanTolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
    # Node selector for scanner pods
    nodeSelector: {}
  # (Future look at creating a TailoredProfile for ZT)
  scanSettingBinding:
    name: compliance-scan-binding
    # Profile in oc get profiles.compliance -n openshift-compliance
    profile: "rhcos4-stig"
  # Storage configuration for scan results
  storage:
    # Enable PVC creation
    enabled: true
    pvc:
      name: compliance-scan-results
      storageClass: ""
      size: "2Gi"
      accessMode: "ReadWriteOnce"

