apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: qtodo
  name: qtodo
  namespace: qtodo
{{- if .Values.app.images.main.registry.auth }}
imagePullSecrets:
  - name: {{ .Values.app.images.main.registry.secretName }}
{{- end }}