{{- if .Values.app.spire.enabled }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: qtodo-truststore-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: '5'
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: {{ .Values.global.secretStore.kind }}
  target:
    name: qtodo-truststore-secret
    template:
      type: Opaque
      data:
        truststore-password: "{{ `{{ .truststore_password }}` }}"
  data:
  - secretKey: truststore_password
    remoteRef:
      key: {{ .Values.app.truststore.vaultPath }}
      property: truststore-password
{{- end }}
