{{- if .Values.distribution.enabled }}
{{- if eq .Values.distribution.method "acm-policy" }}
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: default
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
  labels:
    {{- include "ztvp-certificates.labels" . | nindent 4 }}
spec:
  clusterSet: default
{{- end }}
{{- end }}

