apiVersion: v2
name: qtodo
description: A Helm chart for QTodo - Persistent Todo Application
type: application
version: 0.0.1
appVersion: "1.0.0"
sources:
  - https://github.com/validated-patterns-demos/qtodo
maintainers:
  - name: Zero Trust Valdated Patterns Team
    email: ztvp-arch-group@redhat.com
keywords:
  - web
  - todo
  - quarkus
  - postgresql
  - pattern
annotations:
  category: Application
